#Site settings
baseurl = "https://leejaekyung.github.io/ljkstudio/"
title = "Site Title | ljkstudio"
copyright = "&copy; 2017 Lee Jae Kyung"
theme = "paper-now"
publishDir = "docs"
languageCode = "UTF-8"
canonifyurls = true

[params]
  googleAnalytics   = ""
  pageNotFoundTitle = "404 - Page not found"

  articleTitle= "Upgrading the Construction Execution Procedure: BIM viewer &amp; AR techonology for Installation of Free-form Structure"
  publishDate = "2017-10-18"
  doi         = ""
  github      = ""

[[params.authors]]
    id    = "leejaekyung"
    name  = "LEE JAEKYUNG"
    email = "leejaekyung@ljkstudio.com"
    url   = "http://ljkstudio.com"
    orcid = "0000-0003-4400-0435"

[[params.authors]]
    id    = "park"
    name  = "Park"
    email = ""
    url   = ""
    orcid = "0000-0002-9341-7985"


[[params.affiliations]]
    name       = "Seoul National University of Science and techonology"
    department = "Department of Housing & Urban Development"
    location   = "Seoul, KOREA"
    url        = "http://gsh.seoultech.ac.kr/en/depart/develop/intro/"
    members    = ["leejaekyung","Park"]




[[params.contributions]]
    name = "Methodology"
    url  = "http://dictionary.casrai.org/Contributor_Roles/Methodology"
    contributors = [ "leejaekyung" ]

[[params.contributions]]
    name = "Investigation"
    url  = "http://dictionary.casrai.org/Contributor_Roles/Investigation"
    contributors = [ "leejaekyung", "Park" ]

[[params.contributions]]
    name = "Software"
    url  = "http://dictionary.casrai.org/Contributor_Roles/Software"
    contributors = [ "leejaekyung" ]

[[params.contributions]]
    name = "Writing - original draft"
    url  = "http://dictionary.casrai.org/Contributor_Roles/Writing_%E2%80%93_original_draft"
    contributors = [ "leejaekyung" ]

[[params.contributions]]
    name = "Writing - review & editing"
    url  = "http://dictionary.casrai.org/Contributor_Roles/Writing_%E2%80%93_review_%26_editing"
    contributors = [ "Park" ]
